### ISSUE TITLE
Is Google Yolo opened to public?

### ISSUE THREAD

**Issue by LeCoupa** [zapier/google-yolo-inline#2]
It seems like it is in a private beta right now (and registration are closed). Do you know if it's a feature opened to the public? It may explain why I get an error. :)

**Comment by abegit** [comment]
> It seems like it is in a private beta right now (and registration are closed). Do you know if it's a feature opened to the public? It may explain why I get an error. :)

From what I've read online in StackOverflow, Twitter, & yCombinator.
All of the developers claim it's only reserved for select companies. Possible reason is the clickjacking scenario

https://twitter.com/sirdarckcat/status/994867137704587264
https://stackoverflow.com/questions/50289065/google-yolo-stop-working-the-client-origin-is-not-permitted-to-use-this-api
https://blog.innerht.ml/google-yolo/
https://news.ycombinator.com/item?id=17044518#17045809

**Comment by LeCoupa** [comment]
@abegit Thank you! Do you know when it is planned to be available for all websites?

**Comment by abegit** [comment]
@LeCoupa I haven't found any information related to a release date, and the submission forms for requesting to be on the approved partners list seems to be private.  :(

So we decided to work on a widget to ask users which account they want to log into. Like an account chooser. I could show you a demo video of this when I'm done if you're interested.

Which web framework were you going to implement this for?

**Comment by LeCoupa** [comment]
Yes, sure! I am using Vue.js :)

**Comment by kovaletsyurii** [comment]
Hi there. Do you know, can I use google yolo now, at 2019?

**Comment by LeCoupa** [comment]
They made no announce yet.
